### ISSUE TITLE
featurerequest: Summation

### ISSUE THREAD

**Issue by LEGOAnimal22** [nicolewhite/algebra.js#11]
I am impressed with what you have accomplished with this project. I looked through your code, but I noticed you did not have a summation function. I am only a novice in JavaScript, but I was thinking maybe you could write something like this:
`Expression.prototype.summation = function(var, upper, lower) {}`

**Comment by nicolewhite** [comment]
I don't see why not! Do you want to take a stab at it?

**Comment by LEGOAnimal22** [comment]
Give me a day or so, I'll see what I can whip up.

**Comment by LEGOAnimal22** [comment]
This is what I have so far:
```js
Expression.prototype.summation = function(variable, lower, upper) {
	var thisExpr = this.copy();
	var newExpr = new Expression();
	for(var i = lower; i < upper++; i++) {
		newExpr = newExpr.add(thisExpr.eval({variable:i}));
	}
	return newExpr;
}
```

I've been using this as `summation(new Expression("x"), 3, 6);` and I can't get `Expression.eval` to work.

**Comment by nicolewhite** [comment]
You should try it like this:

```js
var sub = {};
sub[variable] = i;
thisExpr.eval(sub);
```

Also, for readability, I think this is more clear:

```js
for(var i = lower; i < upper + 1; i++) {
...
}

**Comment by LEGOAnimal22** [comment]
I added the function and wrote a test to go with it in #12
