### ISSUE TITLE
Summation error when full expression is parsed

### ISSUE THREAD

**Issue by LEGOAnimal22** [nicolewhite/algebra.js#13]
![summation error](https://cloud.githubusercontent.com/assets/4968240/9395696/2cd82410-474d-11e5-9381-b828b2f2fd6a.png)

When an expression is created the long way(red), the given variable is easily recognized and an answer is given(39 = 8 + 13 + 18). When an expression is parsed by string(yellow), the summation function cannot recognize the given variable, therefore resulting in an incorrect answer. Any thoughts?

**Comment by timrach** [comment]
If you want to create Expressions from a string, you need to call the parse function in algebra.js.
````
var e = algebra.parse("5 * x + 3").summation("x",1,3)
console.log(e.toString()) // == 39
```

**Comment by nicolewhite** [comment]
@timrach is right. When you pass a string to Expression like that, it's being interpreted as a variable. So all of "5x + 3" was a single variable and it was showing you 3 * "5x + 3" as if it were a variable like "x".

**Comment by LEGOAnimal22** [comment]
Thank you for clearing that up :smile:
