### ISSUE TITLE
Suggestion: Don't return undefined if there are infinites solutions

### ISSUE THREAD

**Issue by pmtarantino** [nicolewhite/algebra.js#2]
Hi Nicole. Awesome library! It is really great.

I just have a suggestion. I was reading your documentation and I found in "Solve Anything Else" section that you return undefined in your example. However, x has infinite solutions, so you could return any number and that would be okay.

I didn't your codebase* so I don't know if this is possible, but it could be great if you could separate the cases where the equation has no solutions (undefined would be fine there), or infinite solutions (you could provide any solution that just work). Right now, I can not handle these cases because both returns undefined.

Thank you!

* yet :-)

**Comment by nicolewhite** [comment]
Hello, glad you like it.

In that example there is also a `y` in the equation so solving for `x` should return an expression in terms of `y`. But the solver is still pretty naive, so if the variable (`x` in this case) can't be isolated with arithmetic it gives up and returns undefined.

In the case of infinite solutions, I think I only cover the linear case (need to also cover the higher order polynomials, so I'll do that) and I just return a string "all reals," which is not ideal. I should probably return a number like you suggest. Perhaps I'll just return a `0`?

**Comment by pmtarantino** [comment]
I understand that `y` is in terms of  `x`, but even that, x could be any number, so you could return any pair that validates, like `x = 1`, `y = 1`, and that would be correct.

I don't know return just a 0 because it could trigger some errors if I later use it for multiplication (cancellation) or division (boom!). Maybe `1` as default, or let the user chose it when you start the expresion?

`var expr = new Expression("x", 1);`

**Comment by nicolewhite** [comment]
So I think in the first case you're talking about a feature that doesn't exist (yet). `Equation.solveFor` won't solve for multiple variables at once. You can only solve for one variable at a time.

Good point about the `0`; I'll return a 1 instead.

**Comment by pmtarantino** [comment]
Oops, my mistake then! I thought it did.
