### ISSUE TITLE
Update website examples

### ISSUE THREAD

**Issue by LEGOAnimal22** [nicolewhite/algebra.js#30]
I was thinking we could update the web examples with algebra.parse() since it is much easier to write. For ex.
This:
```js
var z = new Expression("z");
var eq1 = new Equation(z.subtract(4).divide(9), z.add(6));
```

Could become this:
```js
var eq1 = algebra.parse("1/9 * z - 4/9 = z + 6");
```

**Comment by nicolewhite** [comment]
That section is specific to building an equation with separate LHS and RHS sides. The process of building an equation from a string is covered in the parser section.

**Comment by LEGOAnimal22** [comment]
See #33
