### ISSUE TITLE
Do not pollute global namespaces

### ISSUE THREAD

**Issue by Ginden** [nicolewhite/algebra.js#31]
Hi.

While working on fixes I have noticed that global namespace is polluted by at lest following variables:

* `matches` (I have fixed it, pull request coming soon)
* `GREEK_LETTERS` (I have fixed it too, pull request coming soon)
* `Number.prototype.toTex`
* `Array.prototype.toTex`

Can you remove to later ones?

**Comment by nicolewhite** [comment]
I'm not sure I understand. I'll wait for your pull request so I can see what you mean.

**Comment by kevinb7** [comment]
@nicolewhite when you add `.toTex` to `Number.prototype` and `Array.prototype` this adds those methods to all numbers and and arrays.  People tend to avoid this practice because it can lead to weird behaviors if two libraries define `.toTex` on those prototypes.  Whichever is defined last will win which ends up breaking the other library.

**Comment by nicolewhite** [comment]
What's the convention for avoiding this?

**Comment by timrach** [comment]
I think the convention is to not expand standard types at all.

You could transform them to ordinary functions in the helper module instead:
```javascript
//Array.prototype.toTex = function() {
function arrayToTex(arr) {
    return arr.map(function(e){return e.toTex();}).join();
};
```

Besides, I noticed that the two methods are never actually called by the library.
Number.toTex is only called once - in helper-spec to test the function. 
It could be removed without affecting other code.

Array.toTex is called twice in equation-spec to compare test results, so changing the method to a helper function also will not cause any problems.

**Comment by nicolewhite** [comment]
If I remove those methods, however, you won't be able to call `.toTex` on the array of answers. I want to be able to do both `.toString` and `.toTex` on arrays:

```js
var n1 = algebra.parse("x + 5");
var n2 = algebra.parse("x - 3/4");

var quad = new Equation(n1.multiply(n2), 0);

console.log(quad.toString());

var answers = quad.solveFor("x");

console.log("x = " + answers.toString());
console.log("x = " + answers.toTex());
```

```
x^2 + 17/4x - 15/4 = 0
x = -5,3/4
x = -5,\frac{3}{4}
```

So the methods aren't needed internally but they're needed for the above.

**Comment by danielsvane** [comment]
Using algebra.js with myscript.js broke some functionality. I suspected it was some namespacing going on, and after finding this issue, I went and deleted the prototyping on Array and String, which solved my issue.

As @timrach says, you shouldn't overload these, but instead just have a helper function, to avoid namespace errors with other packages.

**Comment by timrach** [comment]
@nicolewhite 

**Suggestion 1**
Maybe you could add a second helper module that is exported by the algebra.js module and contains ```numberToTex``` and ```arrayToTex```, so the conversion to TeX could look like this:
```
...
console.log("x = " + algebra.helper.arrayToTex(answers));
```
That way only the two functions are exposed to users and the array and number namespaces are kept clean. However, it looks strange and will certainly lead to confusion as there would be two ways to convert to TeX.

**Suggestion 2**
A more consistent way would be to expose a ```toTex``` function in the algebra module (or a helper module) that accepts every type as input , so Expressions, Equations..., Arrays and Numbers are all converted in the same way:
```javascript
var expr = new Expression("x");
algebra.toTex(expr) // ---> "x"

var frac = new Fraction(1,3)
algebra.toTex(frac) // ---> "\frac{1}{3}"


var n1 = algebra.parse("x + 5");
var n2 = algebra.parse("x - 3/4");

var quad = new Equation(n1.multiply(n2), 0);
var answers = quad.solveFor("x");

console.log("x = " + algebra.toTex(answers)); //---> x = -5,\frac{3}{4}
```

**Comment by nicolewhite** [comment]
I definitely like the second approach. If no one objects I will make the changes. In the cases of `matches` and `GREEK_LETTERS` it's just because I forgot `var`. I wonder if the linter should be able to catch that?

**Comment by timrach** [comment]
The linter catches that if the keyword 'undef' is set to true in the linting options.

**Comment by nicolewhite** [comment]
I plan on leaving the `toTex` method that's already available on Expressions and Equations so as not to introduce too many breaking changes. The downside is that it's kind of confusing that you can do both of:

```js
var exp = new Expression("x");
exp.toTex()
algebra.toTex(exp);
```

Wdyt?

**Comment by timrach** [comment]
I think that's a reasonable solution.
