### ISSUE TITLE
Coefficients on variables with degree > 1 do not parse correctly

### ISSUE THREAD

**Issue by nicolewhite** [nicolewhite/algebra.js#40]
This is in reference to https://github.com/nicolewhite/algebra.js/issues/37.

```js
algebra.parse("3/2x^2").toString();
"9/4x^2"
algebra.parse("(3/2)x^2").toString();
"9/4x^2"
algebra.parse("(3/2) * x^2").toString();
"9/4x^2"
```

Looks like the degree is being applied to the coefficient.

```js
algebra.parse("(3/2) * x^3").toString();
"27/8x^3"
```

This also affects integers.

```js
algebra.parse("2 * x^3").toString();
"8x^3"
```

**Comment by timrach** [comment]
That's weird...I wrote a test for "(3/2) * x^2" and got the correct result. 
When I parse the same input on http://algebra.js.org/ it returns "9/4x^2".

**Comment by nicolewhite** [comment]
Oops! Maybe I didn't update the version available on gh-pages.

**Comment by timrach** [comment]
Ok, that mystery is solved :smile: 
I already found the section in the parser that causes the bug: It's a problem with the missing 'multiply' operator. I should be able to fix it.

**Comment by nicolewhite** [comment]
Ok. My bad. This is now the behavior I'm seeing:

```js
algebra.parse("3/2x^2").toString()
"9/4x^2"
algebra.parse("3/2*x^2").toString()
"3/2x^2"
```

But this is how it is documented, so I wouldn't call the former example a bug. In the docs I state "You must use the * operator between coefficients and variables."

**Comment by timrach** [comment]
You can remove the line from the docs, I fixed it.
