### ISSUE TITLE
Negative coefficient of variable does not parse

### ISSUE THREAD

**Issue by calvinw** [nicolewhite/algebra.js#41]
In 0.2.4 I have noticed this:

var algebra = require("algebra.js")

This works:
algebra.parse("(-2)*x+3*y=4");

but this does not:
algebra.parse("-2*x+3*y=4");
SyntaxError: Unbalanced Parenthesis

This is a great library...! I am using it and enjoying it tons! Thanks so much for creating this.

**Comment by calvinw** [comment]
Also with stars (*) for multiplication

-2\*x + 3\*y = 4 does not parse

but 

(-2)\*x + 3\*y = 4 does parse

**Comment by timrach** [comment]
Hey, I fixed this bug in #42.
