### ISSUE TITLE
Getting multiple results when the answer should be one

### ISSUE THREAD

**Issue by sonnyk22** [nicolewhite/algebra.js#44]
I need your help regarding this equation: (x^2-5*x+4)/(x+1)/(x-4)=0.
The answer to this equation is only x=1, but AlgebraJS return [4, 1] as seen below:

![calc1](https://cloud.githubusercontent.com/assets/6744710/11543907/21401a24-990d-11e5-94be-0be280dfff17.png)

I even applied extra parsing on my side to this equation prior to passing it into the AlgebraJS.Parse() function, but I ended up getting the same results:

![calc2](https://cloud.githubusercontent.com/assets/6744710/11543929/3feaad7c-990d-11e5-83ba-a45a468cf5b8.png)

**Comment by timrach** [comment]
It's the same problem as in #43: For now, you can not divide by Expressions in algebra.js.
In the parsing step occurances of x as denominator are dropped, returning ```(-1/4)*x^2 + (5/4)*x - 1 = 0``` which is not equal to  ```(x^2-5*x+4)/(x+1)/(x-4)=0```. The solution for x for the parsed equation is calculated correctly: [4,1].
Formatting the input string will not change the fact that in algebra.js you can not divide by expressions containing variables. Sorry.

**Comment by sonnyk22** [comment]
Thanks for getting back to me in this; I hope sometime in the near future, this library will be able to solve this.

In the meantime, is there a way such as a function or a flag that when the end-user enters such a equation such as this, then on my end I can display "invalid equation"?

**Comment by timrach** [comment]
Yes, I'm working on this right now :+1:

**Comment by sonnyk22** [comment]
Fantastic!  Thank you

**Comment by timrach** [comment]
Pull request is out (#45). I'm closing this as it's the same issue as #43 .
