### ISSUE TITLE
The length of numbers allowed by the .parse() function

### ISSUE THREAD

**Issue by sonnyk22** [nicolewhite/algebra.js#46]
In the AlgebraJS library, is there a limitation on the size of numbers when parsing the equations?

Equation 1: cos((5)+(5+2***7))+x^2-6**0+5=0; solving for x.
AlgebraJS parsed equation: x^2 + 5424179007336997/1000000000000000 = 0
![calc1](https://cloud.githubusercontent.com/assets/6744710/11567558/85d7d488-99b5-11e5-87d7-938cf1a4019d.png)

Equation 2: cos((5)+(5+2*7))+x^2-60+5=0; solving for x.
AlgebraJS parsed equation:  x^2 - 54575820992663/1000000000000 = 0
![calc2](https://cloud.githubusercontent.com/assets/6744710/11567560/88ef7ff4-99b5-11e5-95c0-7817df1b74c1.png)

**Comment by timrach** [comment]
What exactly is your question?

``` 0.424179007336997+x^2-6*0+5=0 ```
``` --> 0.424179007336997+x^2+5=0 ```
``` --> 5.424179007336997+x^2=0 ```
The library has no internal representation for decimal numbers other than fractions, so ```5.424179007336997``` is transformed to the fraction ```5424179007336997/1000000000000000```` which is ugly but equal. 

If you are asking why the first equation resulted in an empty solution, that behavior is intended:
```5.424179007336997+x^2=0 ```
```x^2=-5.42417900733699 ``` 
From the [documentation:](http://algebra.js.org/#equations-quadratic) 'Solving a quadratic equation with a discriminant that is less than 0 will return an empty array.'

**Comment by sonnyk22** [comment]
Thank you for your reply on this; you answered my question, "Solving a quadratic equation with a discriminant that is less than 0 will return an empty array."
