### ISSUE TITLE
Interesting related library

### ISSUE THREAD

**Issue by ivanistheone** [nicolewhite/algebra.js#48]
There might be an opportunity to import or combine code with this cool library by Jim Fowler: 
https://github.com/kisonecat/math-expressions

Here are some examples of inputs it supports: https://github.com/kisonecat/math-expressions/blob/master/spec/math-expressions-spec.js

**Comment by nicolewhite** [comment]
Neat. It'll probably be helpful to check out their source code when we run into problems with the parser.
