### ISSUE TITLE
Question regarding sin(x)=0.7

### ISSUE THREAD

**Issue by sonnyk22** [nicolewhite/algebra.js#49]
Is there a way that AlgebraJS is able to solve equations such as sin(x)=0.7 or similar?  If not, what I need to do on my end, so that the latest version of AlgebraJS can solve it?

**Comment by nicolewhite** [comment]
There are no plans to support trigonometric operations in the near future.

**Comment by The-Penultimate-Defenestrator** [comment]
@nicolewhite How hard would this be to implement? I would think that given JavaScript's functions like `Math.sin` and `Math.asin`, this should be fairly trivial, but I don't pretend to understand the workings of this project. Still, I think that this could be a relatively easy thing to check off

Is there a tasklist somewhere describing what *is* planned?
