### ISSUE TITLE
featurerequest: add a fromTeX method to Expression

### ISSUE THREAD

**Issue by ivanistheone** [nicolewhite/algebra.js#5]
It would be cool to have `fromTex` an inverse function of `toTex`.

Instead of:

    var expr1 = new Expression("x").add(3);

one could build and equivalent expression using: 

    var expr2 =  new Expression().fromTex("x + 3")

**Comment by nicolewhite** [comment]
Yeah, that [came up on HN too](https://news.ycombinator.com/item?id=10063277). I'm not sure I'm up for parsing TeX, but I could take a stab at parsing strings.

**Comment by nicolewhite** [comment]
I'm closing this as the conversation about this is happening over in https://github.com/nicolewhite/algebra.js/issues/7. Feel free to jump in over there.
