### ISSUE TITLE
Possible issue when solving x^3-2x^2+x+5=0 

### ISSUE THREAD

**Issue by sonnyk22** [nicolewhite/algebra.js#50]
I believe the result for the equation x^3-2x^2+x+5=0 should be **-1.11634**, instead AlgebraJS returns twice the value which is -2.0235238177480417, as shown below.

**Equation: x^3-2x^2+x+5=0**
![calc1](https://cloud.githubusercontent.com/assets/6744710/13020923/0a29c2aa-d1a6-11e5-9042-87250a45a245.png)

**Result: -2.0235238177480417**
![calc2](https://cloud.githubusercontent.com/assets/6744710/13020924/0b6f103e-d1a6-11e5-863b-6499a2d43ea4.png)

Is there something I can do on my side, so that eq.solveFor("x") function would provide me with this result?

**Comment by nicolewhite** [comment]
Looks like a bug. I'll take a look.

**Comment by mirsaeedi** [comment]
Is there any updates about this issue?
