### ISSUE TITLE
Issue with solving for 4x^4-3x^3+2x^2=1 

### ISSUE THREAD

**Issue by sonnyk22** [nicolewhite/algebra.js#51]
I am having problem getting any result coming back for the equation of 4x^4-3x^3+2x^2=1.  It seems that AlgebraJS is parsing it well, but it is throwing an exception when it is trying to solve, as shown below.

Equation: 4x^4-3x^3+2x^2=1 
![calc1](https://cloud.githubusercontent.com/assets/6744710/13021266/41867dae-d1a8-11e5-88fe-2ada76e0cd84.png)

Result: An exception at this moment
![calc2](https://cloud.githubusercontent.com/assets/6744710/13021287/606ba2f8-d1a8-11e5-8321-741b25e3792b.png)

The answers should be -0.479, 0.7219.  Is there something I can do on my side, so that eq.solveFor("x") function would provide results?

**Comment by nicolewhite** [comment]
It doesn't solve quartics yet. See https://github.com/nicolewhite/algebra.js/issues/10.
