### ISSUE TITLE
Possible parsing issue for 2^x=10

### ISSUE THREAD

**Issue by sonnyk22** [nicolewhite/algebra.js#52]
I believe that the AlgebraJS may be having parsing issue with smaller equations such as 2^x=10, or 2.71^x=15, as shown below.

Equation: 2^x=10
![calc1](https://cloud.githubusercontent.com/assets/6744710/13021642/3eaef834-d1aa-11e5-84b1-3bb87b1a49be.png)

Result:  An exception at the moment
![calc2](https://cloud.githubusercontent.com/assets/6744710/13021655/4e9744f4-d1aa-11e5-824c-dcd523188e2a.png)

Is there something I can do on my side, so that eq.solveFor("x") function would provide a result?

**Comment by nicolewhite** [comment]
There are no plans to support variables as exponents in the near future. As the error suggests, "Exponent must be of type Integer."
