### ISSUE TITLE
Possible parsing issue for 2^(2x)-2^x-2=0

### ISSUE THREAD

**Issue by sonnyk22** [nicolewhite/algebra.js#53]
This may be the same issue as in #52.   The library is failing to parse for either 2^(2x)-2^x-2=0, or (2^(2x))-2^x-2=0, as shown below.

Equation: 2^(2x)-2^x-2=0
![calc1](https://cloud.githubusercontent.com/assets/6744710/13022266/2a713298-d1ae-11e5-83de-15a60e63bb66.png)

Result:  An exception at the moment
![calc2](https://cloud.githubusercontent.com/assets/6744710/13022267/2ce0291c-d1ae-11e5-91b7-0f044207216d.png)

Would you help me with this issue?

**Comment by nicolewhite** [comment]
There are no plans to support variables as exponents in the near future.
