### ISSUE TITLE
Can algebra.js file work in browser?

### ISSUE THREAD

**Issue by pvnr0082t** [nicolewhite/algebra.js#57]
Hi @nicolewhite ,
We are [cdnjs](https://github.com/cdnjs/cdnjs) team. We want to host this library.
Because the algebra.js file includes files in `src` folder, we want to know if it can work in browser without files in `src` folder. Could you please tell us whether files in `src` folder need to be added in cdnjs?
Thank you.

https://github.com/cdnjs/cdnjs/issues/7971
https://github.com/cdnjs/cdnjs/pull/8152

**Comment by nicolewhite** [comment]
Hello, sorry, I don't have a lot of free time to maintain this project anymore. Can you help me understand what's changed recently with browsers loading JavaScript files? My current setup worked when I built this project a few months ago. I simply loaded the minified js like so:

```html
<script src="javascripts/algebra.min.js"></script>
```

Now this no longer works and I get undefined errors.

**Comment by pvskand** [comment]
@nicolewhite exactly! This is the problem that I am facing! It shows **Equation is not defined** or **Expression is not defined** even though I load the minified js file properly.

**Comment by nicolewhite** [comment]
[I updated the dependencies](https://github.com/nicolewhite/algebra.js/commit/166191f20783f203b790b3b80c10d2faeb2296e3) and all seems to be well. A new minified file has been uploaded to http://algebra.js.org/ and works correctly in the browser (only tested on Chrome).
