### ISSUE TITLE
algebra.min.js throwing undefined error on Chrome

### ISSUE THREAD

**Issue by pvskand** [nicolewhite/algebra.js#59]
I know that you had updated the dependencies, but unfortunately I have tried working with the updated version of the minified js file and it is still showing the **Equation not defined** error.
Is there any other way I can work this out? 
I have even tried on my friend's laptop and it is still not working!
Below is the error shown for the line `var eq = new Equation(x1, x2);`
![selection_002](https://cloud.githubusercontent.com/assets/14890185/16406809/037c5a78-3d2e-11e6-98ce-1803fd58a12f.png)

**Comment by dominik0711** [comment]
The minified version is pointing to `./src` folder which is **NOT** available next to your `algebra.min.js`! The minifying of the library is **not** correct. There shouldn't be any external dependency in `algebra.min.js`

**Comment by pvskand** [comment]
After adding the new version of 0.2.5 minified js, the undefined error aren't being shown. I had forgotten to define Equation and Expression.

**Comment by nicolewhite** [comment]
Oops, I meant to reply to this issue as well. I'm glad you figured it out. See my explanation: https://github.com/nicolewhite/algebra.js/issues/60#issuecomment-229081545
