### ISSUE TITLE
Cannot read 'Render' property

### ISSUE THREAD

**Issue by pvskand** [nicolewhite/algebra.js#61]
I have used the sample code given in your Docs bu there is this error showing up saying that **Cannot read property render**. Should we define it like `var render = new algebra.render`? I did that as well but wasn't able to rectify the error.

```
<script >
var Fraction = algebra.Fraction;
var Expression = algebra.Expression;
var Equation = algebra.Equation;
var katex = algebra.katex;
var render = algebra.render;


var lambda = new Expression("lambda").add(3).divide(4);
var Phi = new Expression("Phi").subtract(new Fraction(1, 5)).add(lambda);

katex.render(algebra.toTex(lambda), expr1);
katex.render(algebra.toTex(Phi), expr2);
</script>
```
```
<div id="expr1"></div>
    <div id="expr2"></div>
```

**Comment by nicolewhite** [comment]
There is no `render` property in this library. That is a `katex` method.

**Comment by pvskand** [comment]
Why is this error showing up?
![image](https://cloud.githubusercontent.com/assets/14890185/16440530/5f64fea0-3de0-11e6-9eca-13aabd98cd97.png)

**Comment by nicolewhite** [comment]
Please read the docs more closely. That example is using KaTeX, another library. Remove these lines:

```
var katex = algebra.katex;
var render = algebra.render;
```

This library doesn't have either of those methods.

**Comment by pvskand** [comment]
Okay I am sorry for not reading the Docs properly. I thought KaTeX was a part of algebra.js. My bad!

**Comment by nicolewhite** [comment]
From their docs [over here](https://github.com/Khan/KaTeX) you can include KaTeX in your HTML easily:

```html
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.6.0/katex.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.6.0/katex.min.js"></script>
```

At that point you should be able to use `katex.render` in a `<script>` tag like I do in the docs:

```html
<script>
katex.render(...)
</script>
```
