### ISSUE TITLE
ReferenceError: Expression is not defined

### ISSUE THREAD

**Issue by saurabhvyas** [nicolewhite/algebra.js#63]
I just downloaded algebra.min.js and referenced it in my index.html file then I tried one of the examples from your website but I keep getting this error on firefox

here is my index.html
```
<!DOCTYPE html>


<head>

    <meta charset="utf-8"/>

<script src="algebra.min.js" >  </script>

<script src="test.js" >  </script>

<title> Err. Interrupter </title>



</head>


<body>

<h1> Err. Interrupter </h1>

<h2> What is 2x + 3 = 5 ? </h2>




</body>

<script>




</script>

</html>

```

**Comment by nicolewhite** [comment]
What is in `test.js`?

**Comment by saurabhvyas** [comment]
console.log('test'); just this

**Comment by nicolewhite** [comment]
I don't see where you reference `Expression`, then. :(

**Comment by saurabhvyas** [comment]
I am sorry Here is the code again 
```
<!DOCTYPE html>


<head>

    <meta charset="utf-8"/>

<script src="algebra-0.2.5.min(1).js"></script>


<script>


var expr = new Expression("x");
expr = expr.subtract(3);
expr = expr.add("x");

console.log(expr.toString());


</script>






<title> Err. Interrupter </title>



</head>


<body>


<h2> What is 2x + 3 = 5 ? </h2>



</body>


</html>

```
My folder structure looks something like this :
![capture](https://cloud.githubusercontent.com/assets/6899784/17942185/f772572a-6a53-11e6-8252-9ace9a732ead.PNG)

**Comment by nicolewhite** [comment]
You need to define `Expression.` Try adding `var Expression = algebra.Expression.`

**Comment by saurabhvyas** [comment]
Okay algebra.Expression solved the problem It would be great if can update the docs so other users dont face similar problem

**Comment by nicolewhite** [comment]
[It is in the documentation](http://algebra.js.org/#getting-started). Thanks!
