### ISSUE TITLE
Formula support? 

### ISSUE THREAD

**Issue by guy-kdm** [nicolewhite/algebra.js#64]
Hi there! I was thinking about adding formula and formula simplification support, as in defining a multi variable expression or equation and having solveFor return an expression (if it is linear or quadratic in regards to the solved variable), also adding domains of definition to each solution expression. Does that make sense (and doesn't already exist somehow)?

**Comment by nicolewhite** [comment]
If I understand you correctly, I *think* that already exists? At least the part about `solveFor` returning an expression:

```
var e = new Expression('x').add('y');
var eq = new Equation(e, 3);
eq.toString();
"x + y = 3"
eq.solveFor('x').toString();
"-y + 3"
```
