### ISSUE TITLE
Provide minified files for old versions

### ISSUE THREAD

**Issue by pvnr0082t** [nicolewhite/algebra.js#69]
Hi @nicolewhite ,
I'm a member of [cdnjs](http://github.com/cdnjs/cdnjs). Because we usually host all versions of the library, is it possible to provide the minified files for old versions? I can just grab the latest version(v0.2.6) from http://algebra.js.org/.
BTW, is it possible to put the minified files on GitHub repo or publish on NPM for the future update, because the auto-updater in cdnjs will update libraries automatically from GitHub or NPM.
Thank you.

https://github.com/cdnjs/cdnjs/issues/7971
https://github.com/cdnjs/cdnjs/pull/8152

**Comment by nicolewhite** [comment]
Hey, the latest stable release is kept at: https://github.com/nicolewhite/algebra.js/tree/gh-pages/javascripts

Is that sufficient?

I'll have to go through my tags to generate all the minified files of older versions. Will get to that in the next few days.

**Comment by nicolewhite** [comment]
Also ya I publish to npm, it's at https://www.npmjs.com/package/algebra.js

**Comment by pvnr0082t** [comment]
@nicolewhite Okay, thanks for your help. :smile: Waiting for the minified files of old versions. Please notify me if done. Many thanks. :tada:

**Comment by nicolewhite** [comment]
@pvnr0082t 

Is having this package on npm sufficient? All past versions are accessible through npm.

**Comment by pvnr0082t** [comment]
@nicolewhite The old versions are accessible on NPM, but it still need to be manually bundled to work on the browser.  It will be good if bundled `algebra.js` and `algebra.min.js` can be directly published on NPM and the auto-updater can automatically update for the lib through NPM. 
Thanks.

**Comment by pvnr0082t** [comment]
@nicolewhite Any update about publish bundled `algebra.js` and `algebra.min.js` on NPM? Thanks.

**Comment by nicolewhite** [comment]
@pvnr0082t I put them here...

https://github.com/nicolewhite/algebra.js/tree/master/build

I am not sure how to put them on npm retroactively. Do you have some documentation on this perhaps? Some initial searches aren't very helpful.
