### ISSUE TITLE
Invalid Argument (0.5): Can only evaluate Expressions or Fractions.

### ISSUE THREAD

**Issue by abhikhatri** [nicolewhite/algebra.js#71]
I was using algebra js to solve linear equations with one variable it's a really great library, but I came around this weird issue. It don't let me use decimal values for variable.

Here's the equation I was using

`var expr = algebra.parse('y=2+x^2');`

`expr.eval({x: '0.5'}).toString();`

it throws following error

`Uncaught TypeError: Invalid Argument (0.5): Can only evaluate Expressions or Fractions.`

I would appreciate any kind of solution to this problem. Thanks in advance :)

**Comment by Kiousis** [comment]
`expr.eval({x: 0.5}).toString();`

0.5 not '0.5'

**Comment by nicolewhite** [comment]
Right. You can do that or

```
half = new Fraction(1, 2);
expr.eval({x: half}).toString();
```

**Comment by abhikhatri** [comment]
@Kiousis I tried without quotes, It was still throwing the same error.

@nicolewhite Your method worked perfectly 👍
