### ISSUE TITLE
Algebraic power does not work for fractions and decimal

### ISSUE THREAD

**Issue by Amruthraj1** [nicolewhite/algebra.js#75]
For a decimal value, The power does not work. 
If we have 
var exp3 = new Expression("x");
var power = exp3.pow(1/0.258);
I get an error that the power argument must be an integer
Infact, the whole algebra.js works only for integer numbers and not for floating point numbers

**Comment by nicolewhite** [comment]
Yeah, that is not supported because the package does not support irrational numbers.
